post http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RwZXJzb24iLCJpZCI6IjY1NWRkZTY0MjQxNDNlNTFhMWI2ZDg1ZSIsImlhdCI6MTcwMDgyNDM3MX0.eedp4cIQ9H6mmBTRwap189A-HKMc7axgp920TRgOJqw

{
    "title": "Test title 3",
    "author": "Test author 3",
    "url": "Test url 3",
    "likes": 1127
}